-- Create news table for storing company news articles
CREATE TABLE news (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    asset_id BIGINT NULL,
    market_data_id BIGINT NULL,
    symbol VARCHAR(20) NOT NULL,
    title VARCHAR(500) NOT NULL,
    summary TEXT,
    link VARCHAR(1000),
    image_url VARCHAR(1000),
    source_api VARCHAR(50),
    publisher VARCHAR(200),
    published_date DATETIME(6),
    category VARCHAR(50),
    article_type VARCHAR(50),
    sentiment VARCHAR(20),
    related_tickers VARCHAR(500),
    is_read BIT DEFAULT 0,
    is_important BIT DEFAULT 0,
    created_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    updated_date DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_symbol (symbol),
    INDEX idx_published_date (published_date),
    INDEX idx_source (source_api),
    INDEX idx_asset_id (asset_id),
    INDEX idx_market_data_id (market_data_id),
    UNIQUE KEY uk_link (link(500)),
    FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE SET NULL,
    FOREIGN KEY (market_data_id) REFERENCES market_data(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
